// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// Bank is an object representing the database table.
type Bank struct {
	ID        int        `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name      string     `boil:"name" json:"name" toml:"name" yaml:"name"`
	Address   string     `boil:"address" json:"address" toml:"address" yaml:"address"`
	Info      types.JSON `boil:"info" json:"info" toml:"info" yaml:"info"`
	CreatedAt time.Time  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time  `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *bankR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L bankL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BankColumns = struct {
	ID        string
	Name      string
	Address   string
	Info      string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Name:      "name",
	Address:   "address",
	Info:      "info",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var BankTableColumns = struct {
	ID        string
	Name      string
	Address   string
	Info      string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "banks.id",
	Name:      "banks.name",
	Address:   "banks.address",
	Info:      "banks.info",
	CreatedAt: "banks.created_at",
	UpdatedAt: "banks.updated_at",
}

// Generated where

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var BankWhere = struct {
	ID        whereHelperint
	Name      whereHelperstring
	Address   whereHelperstring
	Info      whereHelpertypes_JSON
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint{field: "\"banks\".\"id\""},
	Name:      whereHelperstring{field: "\"banks\".\"name\""},
	Address:   whereHelperstring{field: "\"banks\".\"address\""},
	Info:      whereHelpertypes_JSON{field: "\"banks\".\"info\""},
	CreatedAt: whereHelpertime_Time{field: "\"banks\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"banks\".\"updated_at\""},
}

// BankRels is where relationship names are stored.
var BankRels = struct {
	Accounts             string
	FromBankTransactions string
	ToBankTransactions   string
}{
	Accounts:             "Accounts",
	FromBankTransactions: "FromBankTransactions",
	ToBankTransactions:   "ToBankTransactions",
}

// bankR is where relationships are stored.
type bankR struct {
	Accounts             AccountSlice     `boil:"Accounts" json:"Accounts" toml:"Accounts" yaml:"Accounts"`
	FromBankTransactions TransactionSlice `boil:"FromBankTransactions" json:"FromBankTransactions" toml:"FromBankTransactions" yaml:"FromBankTransactions"`
	ToBankTransactions   TransactionSlice `boil:"ToBankTransactions" json:"ToBankTransactions" toml:"ToBankTransactions" yaml:"ToBankTransactions"`
}

// NewStruct creates a new relationship struct
func (*bankR) NewStruct() *bankR {
	return &bankR{}
}

func (r *bankR) GetAccounts() AccountSlice {
	if r == nil {
		return nil
	}
	return r.Accounts
}

func (r *bankR) GetFromBankTransactions() TransactionSlice {
	if r == nil {
		return nil
	}
	return r.FromBankTransactions
}

func (r *bankR) GetToBankTransactions() TransactionSlice {
	if r == nil {
		return nil
	}
	return r.ToBankTransactions
}

// bankL is where Load methods for each relationship are stored.
type bankL struct{}

var (
	bankAllColumns            = []string{"id", "name", "address", "info", "created_at", "updated_at"}
	bankColumnsWithoutDefault = []string{"name", "address", "info"}
	bankColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	bankPrimaryKeyColumns     = []string{"id"}
	bankGeneratedColumns      = []string{}
)

type (
	// BankSlice is an alias for a slice of pointers to Bank.
	// This should almost always be used instead of []Bank.
	BankSlice []*Bank
	// BankHook is the signature for custom Bank hook methods
	BankHook func(context.Context, boil.ContextExecutor, *Bank) error

	bankQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	bankType                 = reflect.TypeOf(&Bank{})
	bankMapping              = queries.MakeStructMapping(bankType)
	bankPrimaryKeyMapping, _ = queries.BindMapping(bankType, bankMapping, bankPrimaryKeyColumns)
	bankInsertCacheMut       sync.RWMutex
	bankInsertCache          = make(map[string]insertCache)
	bankUpdateCacheMut       sync.RWMutex
	bankUpdateCache          = make(map[string]updateCache)
	bankUpsertCacheMut       sync.RWMutex
	bankUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var bankAfterSelectMu sync.Mutex
var bankAfterSelectHooks []BankHook

var bankBeforeInsertMu sync.Mutex
var bankBeforeInsertHooks []BankHook
var bankAfterInsertMu sync.Mutex
var bankAfterInsertHooks []BankHook

var bankBeforeUpdateMu sync.Mutex
var bankBeforeUpdateHooks []BankHook
var bankAfterUpdateMu sync.Mutex
var bankAfterUpdateHooks []BankHook

var bankBeforeDeleteMu sync.Mutex
var bankBeforeDeleteHooks []BankHook
var bankAfterDeleteMu sync.Mutex
var bankAfterDeleteHooks []BankHook

var bankBeforeUpsertMu sync.Mutex
var bankBeforeUpsertHooks []BankHook
var bankAfterUpsertMu sync.Mutex
var bankAfterUpsertHooks []BankHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Bank) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bankAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Bank) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bankBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Bank) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bankAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Bank) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bankBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Bank) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bankAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Bank) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bankBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Bank) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bankAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Bank) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bankBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Bank) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bankAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBankHook registers your hook function for all future operations.
func AddBankHook(hookPoint boil.HookPoint, bankHook BankHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		bankAfterSelectMu.Lock()
		bankAfterSelectHooks = append(bankAfterSelectHooks, bankHook)
		bankAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		bankBeforeInsertMu.Lock()
		bankBeforeInsertHooks = append(bankBeforeInsertHooks, bankHook)
		bankBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		bankAfterInsertMu.Lock()
		bankAfterInsertHooks = append(bankAfterInsertHooks, bankHook)
		bankAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		bankBeforeUpdateMu.Lock()
		bankBeforeUpdateHooks = append(bankBeforeUpdateHooks, bankHook)
		bankBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		bankAfterUpdateMu.Lock()
		bankAfterUpdateHooks = append(bankAfterUpdateHooks, bankHook)
		bankAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		bankBeforeDeleteMu.Lock()
		bankBeforeDeleteHooks = append(bankBeforeDeleteHooks, bankHook)
		bankBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		bankAfterDeleteMu.Lock()
		bankAfterDeleteHooks = append(bankAfterDeleteHooks, bankHook)
		bankAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		bankBeforeUpsertMu.Lock()
		bankBeforeUpsertHooks = append(bankBeforeUpsertHooks, bankHook)
		bankBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		bankAfterUpsertMu.Lock()
		bankAfterUpsertHooks = append(bankAfterUpsertHooks, bankHook)
		bankAfterUpsertMu.Unlock()
	}
}

// OneG returns a single bank record from the query using the global executor.
func (q bankQuery) OneG(ctx context.Context) (*Bank, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single bank record from the query.
func (q bankQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Bank, error) {
	o := &Bank{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for banks")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Bank records from the query using the global executor.
func (q bankQuery) AllG(ctx context.Context) (BankSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all Bank records from the query.
func (q bankQuery) All(ctx context.Context, exec boil.ContextExecutor) (BankSlice, error) {
	var o []*Bank

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Bank slice")
	}

	if len(bankAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Bank records in the query using the global executor
func (q bankQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all Bank records in the query.
func (q bankQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count banks rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q bankQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q bankQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if banks exists")
	}

	return count > 0, nil
}

// Accounts retrieves all the account's Accounts with an executor.
func (o *Bank) Accounts(mods ...qm.QueryMod) accountQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"accounts\".\"bank_id\"=?", o.ID),
	)

	return Accounts(queryMods...)
}

// FromBankTransactions retrieves all the transaction's Transactions with an executor via from_bank_id column.
func (o *Bank) FromBankTransactions(mods ...qm.QueryMod) transactionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"transactions\".\"from_bank_id\"=?", o.ID),
	)

	return Transactions(queryMods...)
}

// ToBankTransactions retrieves all the transaction's Transactions with an executor via to_bank_id column.
func (o *Bank) ToBankTransactions(mods ...qm.QueryMod) transactionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"transactions\".\"to_bank_id\"=?", o.ID),
	)

	return Transactions(queryMods...)
}

// LoadAccounts allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (bankL) LoadAccounts(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBank interface{}, mods queries.Applicator) error {
	var slice []*Bank
	var object *Bank

	if singular {
		var ok bool
		object, ok = maybeBank.(*Bank)
		if !ok {
			object = new(Bank)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBank)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBank))
			}
		}
	} else {
		s, ok := maybeBank.(*[]*Bank)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBank)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBank))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &bankR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &bankR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`accounts`),
		qm.WhereIn(`accounts.bank_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load accounts")
	}

	var resultSlice []*Account
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice accounts")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on accounts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for accounts")
	}

	if len(accountAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Accounts = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &accountR{}
			}
			foreign.R.Bank = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.BankID {
				local.R.Accounts = append(local.R.Accounts, foreign)
				if foreign.R == nil {
					foreign.R = &accountR{}
				}
				foreign.R.Bank = local
				break
			}
		}
	}

	return nil
}

// LoadFromBankTransactions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (bankL) LoadFromBankTransactions(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBank interface{}, mods queries.Applicator) error {
	var slice []*Bank
	var object *Bank

	if singular {
		var ok bool
		object, ok = maybeBank.(*Bank)
		if !ok {
			object = new(Bank)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBank)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBank))
			}
		}
	} else {
		s, ok := maybeBank.(*[]*Bank)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBank)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBank))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &bankR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &bankR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`transactions`),
		qm.WhereIn(`transactions.from_bank_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load transactions")
	}

	var resultSlice []*Transaction
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice transactions")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on transactions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for transactions")
	}

	if len(transactionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.FromBankTransactions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &transactionR{}
			}
			foreign.R.FromBank = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.FromBankID {
				local.R.FromBankTransactions = append(local.R.FromBankTransactions, foreign)
				if foreign.R == nil {
					foreign.R = &transactionR{}
				}
				foreign.R.FromBank = local
				break
			}
		}
	}

	return nil
}

// LoadToBankTransactions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (bankL) LoadToBankTransactions(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBank interface{}, mods queries.Applicator) error {
	var slice []*Bank
	var object *Bank

	if singular {
		var ok bool
		object, ok = maybeBank.(*Bank)
		if !ok {
			object = new(Bank)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBank)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBank))
			}
		}
	} else {
		s, ok := maybeBank.(*[]*Bank)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBank)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBank))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &bankR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &bankR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`transactions`),
		qm.WhereIn(`transactions.to_bank_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load transactions")
	}

	var resultSlice []*Transaction
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice transactions")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on transactions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for transactions")
	}

	if len(transactionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ToBankTransactions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &transactionR{}
			}
			foreign.R.ToBank = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ToBankID {
				local.R.ToBankTransactions = append(local.R.ToBankTransactions, foreign)
				if foreign.R == nil {
					foreign.R = &transactionR{}
				}
				foreign.R.ToBank = local
				break
			}
		}
	}

	return nil
}

// AddAccountsG adds the given related objects to the existing relationships
// of the bank, optionally inserting them as new records.
// Appends related to o.R.Accounts.
// Sets related.R.Bank appropriately.
// Uses the global database handle.
func (o *Bank) AddAccountsG(ctx context.Context, insert bool, related ...*Account) error {
	return o.AddAccounts(ctx, boil.GetContextDB(), insert, related...)
}

// AddAccounts adds the given related objects to the existing relationships
// of the bank, optionally inserting them as new records.
// Appends related to o.R.Accounts.
// Sets related.R.Bank appropriately.
func (o *Bank) AddAccounts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Account) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.BankID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"accounts\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"bank_id"}),
				strmangle.WhereClause("\"", "\"", 2, accountPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.AccountNumber}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.BankID = o.ID
		}
	}

	if o.R == nil {
		o.R = &bankR{
			Accounts: related,
		}
	} else {
		o.R.Accounts = append(o.R.Accounts, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &accountR{
				Bank: o,
			}
		} else {
			rel.R.Bank = o
		}
	}
	return nil
}

// AddFromBankTransactionsG adds the given related objects to the existing relationships
// of the bank, optionally inserting them as new records.
// Appends related to o.R.FromBankTransactions.
// Sets related.R.FromBank appropriately.
// Uses the global database handle.
func (o *Bank) AddFromBankTransactionsG(ctx context.Context, insert bool, related ...*Transaction) error {
	return o.AddFromBankTransactions(ctx, boil.GetContextDB(), insert, related...)
}

// AddFromBankTransactions adds the given related objects to the existing relationships
// of the bank, optionally inserting them as new records.
// Appends related to o.R.FromBankTransactions.
// Sets related.R.FromBank appropriately.
func (o *Bank) AddFromBankTransactions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Transaction) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.FromBankID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"transactions\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"from_bank_id"}),
				strmangle.WhereClause("\"", "\"", 2, transactionPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.FromBankID = o.ID
		}
	}

	if o.R == nil {
		o.R = &bankR{
			FromBankTransactions: related,
		}
	} else {
		o.R.FromBankTransactions = append(o.R.FromBankTransactions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &transactionR{
				FromBank: o,
			}
		} else {
			rel.R.FromBank = o
		}
	}
	return nil
}

// AddToBankTransactionsG adds the given related objects to the existing relationships
// of the bank, optionally inserting them as new records.
// Appends related to o.R.ToBankTransactions.
// Sets related.R.ToBank appropriately.
// Uses the global database handle.
func (o *Bank) AddToBankTransactionsG(ctx context.Context, insert bool, related ...*Transaction) error {
	return o.AddToBankTransactions(ctx, boil.GetContextDB(), insert, related...)
}

// AddToBankTransactions adds the given related objects to the existing relationships
// of the bank, optionally inserting them as new records.
// Appends related to o.R.ToBankTransactions.
// Sets related.R.ToBank appropriately.
func (o *Bank) AddToBankTransactions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Transaction) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ToBankID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"transactions\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"to_bank_id"}),
				strmangle.WhereClause("\"", "\"", 2, transactionPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ToBankID = o.ID
		}
	}

	if o.R == nil {
		o.R = &bankR{
			ToBankTransactions: related,
		}
	} else {
		o.R.ToBankTransactions = append(o.R.ToBankTransactions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &transactionR{
				ToBank: o,
			}
		} else {
			rel.R.ToBank = o
		}
	}
	return nil
}

// Banks retrieves all the records using an executor.
func Banks(mods ...qm.QueryMod) bankQuery {
	mods = append(mods, qm.From("\"banks\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"banks\".*"})
	}

	return bankQuery{q}
}

// FindBankG retrieves a single record by ID.
func FindBankG(ctx context.Context, iD int, selectCols ...string) (*Bank, error) {
	return FindBank(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindBank retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBank(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Bank, error) {
	bankObj := &Bank{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"banks\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, bankObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from banks")
	}

	if err = bankObj.doAfterSelectHooks(ctx, exec); err != nil {
		return bankObj, err
	}

	return bankObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Bank) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Bank) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no banks provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bankColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	bankInsertCacheMut.RLock()
	cache, cached := bankInsertCache[key]
	bankInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			bankAllColumns,
			bankColumnsWithDefault,
			bankColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(bankType, bankMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(bankType, bankMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"banks\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"banks\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into banks")
	}

	if !cached {
		bankInsertCacheMut.Lock()
		bankInsertCache[key] = cache
		bankInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Bank record using the global executor.
// See Update for more documentation.
func (o *Bank) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the Bank.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Bank) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	bankUpdateCacheMut.RLock()
	cache, cached := bankUpdateCache[key]
	bankUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			bankAllColumns,
			bankPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update banks, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"banks\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, bankPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(bankType, bankMapping, append(wl, bankPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update banks row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for banks")
	}

	if !cached {
		bankUpdateCacheMut.Lock()
		bankUpdateCache[key] = cache
		bankUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q bankQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q bankQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for banks")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for banks")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o BankSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BankSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bankPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"banks\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, bankPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in bank slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all bank")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Bank) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Bank) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no banks provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bankColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	bankUpsertCacheMut.RLock()
	cache, cached := bankUpsertCache[key]
	bankUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			bankAllColumns,
			bankColumnsWithDefault,
			bankColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			bankAllColumns,
			bankPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert banks, could not build update column list")
		}

		ret := strmangle.SetComplement(bankAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(bankPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert banks, could not build conflict column list")
			}

			conflict = make([]string, len(bankPrimaryKeyColumns))
			copy(conflict, bankPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"banks\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(bankType, bankMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(bankType, bankMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert banks")
	}

	if !cached {
		bankUpsertCacheMut.Lock()
		bankUpsertCache[key] = cache
		bankUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Bank record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Bank) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single Bank record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Bank) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Bank provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), bankPrimaryKeyMapping)
	sql := "DELETE FROM \"banks\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from banks")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for banks")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q bankQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q bankQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no bankQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from banks")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for banks")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o BankSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BankSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(bankBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bankPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"banks\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, bankPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from bank slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for banks")
	}

	if len(bankAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Bank) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no Bank provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Bank) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBank(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BankSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty BankSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BankSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BankSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bankPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"banks\".* FROM \"banks\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, bankPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BankSlice")
	}

	*o = slice

	return nil
}

// BankExistsG checks if the Bank row exists.
func BankExistsG(ctx context.Context, iD int) (bool, error) {
	return BankExists(ctx, boil.GetContextDB(), iD)
}

// BankExists checks if the Bank row exists.
func BankExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"banks\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if banks exists")
	}

	return exists, nil
}

// Exists checks if the Bank row exists.
func (o *Bank) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return BankExists(ctx, exec, o.ID)
}
