// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accounts            string
	Banks               string
	TransactionStatuses string
	TransactionTypes    string
	Transactions        string
}{
	Accounts:            "accounts",
	Banks:               "banks",
	TransactionStatuses: "transaction_statuses",
	TransactionTypes:    "transaction_types",
	Transactions:        "transactions",
}
